name: Release Build

on:
  push:
    branches: 
      - develop
  # 手动触发


jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add signing properties
        env:
          SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
        run: |
          echo ${{ secrets.SIGNING_PROPERTIES }} > encoded_signing_properties
          base64 -d encoded_signing_properties > signing.properties

      - name: Add jks file
        run: |
          echo ${{ secrets.SIGN_KEY }} > ./encoded_key
          base64 -d encoded_key > key.jks

      - name: Build APK
        run: ./gradlew assembleRelease


  #发布构建的app
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v2
        with:
            name: Release_${{ env.VERSION }}.apk
            path: ${{ github.workspace }}/app/build/outputs/apk/release/${{ env.APK_FILE }}
