name: Release Build

on:
  push:
    branches: 
      - develop
  # 手动触发
  workflow_dispatch:

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  # 构建app
      - name: Build app
        run: bash ./gradlew assembleRelease

  #发布构建的app
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v2
        with:
            name: Release_${{ env.VERSION }}.apk
            path: ${{ github.workspace }}/app/build/outputs/apk/release/${{ env.APK_FILE }}
